---
- name: "priority::high"
  description: "High priority"
  color: "FF33CC"

- name: "priority::medium"
  description: "Medium priority"
  color: "FFFF33"

- name: "priority::low"
  description: "Low priority"
  color: "66FF66"

- name: "update::major"
  description: "Major update"
  color: "00FFFF"

- name: "update::minor"
  description: "Minor update"
  color: "0099CC"

- name: "update::patch"
  description: "Patch update"
  color: "003366"

- name: "ci"
  description: "Changes to CI workflows"
  color: "FFD580"

- name: "pre-commit"
  description: "Changes to pre-commit hooks"
  color: "FFD580"

- name: "documentation"
  description: "Improvements or additions to documentation"
  color: "CCE5F5"

- name: "bug"
  description: "Something isn't working"
  color: "FF3333"

- name: "automated"
  description: "Automated issue or pull request"
  color: "D6D6D6"

- name: "dependencies"
  description: "Update dependencies"
  color: "D6D6D6"

- name: "versioning"
  description: "Versioning changes"
  color: "D6D6D6"
