"ci":
  - changed-files:
    - any-glob-to-any-file: [".github/workflows/**"]

"pre-commit":
  - changed-files:
    - any-glob-to-any-file: [".pre-commit-config.yaml"]

"documentation":
  - changed-files:
    - any-glob-to-any-file: "**/*.md"

"versioning":
  - changed-files:
    - any-glob-to-any-file: ".bumpversion.toml"
