name: Bump Version

on:
  pull_request:
    types: [closed]

jobs:

  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: conjikidow/bump-version-action@82f8dcf6a8b9e2d2102d5fba70dafabd5ec59342 # v3.0.0
        with:
          label-major: 'update::major'
          label-minor: 'update::minor'
          label-patch: 'update::patch'
          labels-to-add: 'automated,versioning'
          create-release: 'true'
