name: Bump Version

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:

  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: conjikidow/bump-version-action@ecaaa809029ee948812b3372bfbbe9fd09dddfa7 # v3.1.0
        with:
          label-major: 'update::major'
          label-minor: 'update::minor'
          label-patch: 'update::patch'
          manual-bump-type: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.bump_type || '' }}
          labels-to-add: 'automated,versioning'
          create-release: 'true'
