name: Label Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:

  labeler:
    name: labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels/labeler.yaml
          sync-labels: false
          dot: true
