name: Label Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:

  labeler:
    name: labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels/labeler.yaml
          sync-labels: false
          dot: true
