name: Sync Template Repository

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  sync-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@8ec19a5f2721ffb81ff809aa340ddf75e6a85ea6 # v2.5.2
        with:
          source_repo_path: conjikidow/typst-repository-template
          upstream_branch: main
          pr_branch_name_prefix: 'workflow/sync-template'
          pr_labels: 'automated,template-sync'
